"""add activation_link

Revision ID: 09ef42cf4a1d
Revises: 7edd8973ef32
Create Date: 2025-06-02 00:31:48.597933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09ef42cf4a1d"
down_revision: Union[str, None] = "7edd8973ef32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("activation_link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "activation_link")
    # ### end Alembic commands ###
