networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: granite_backend
    ports:
      - "8000:8000"
    environment:
      - DB__URL=postgresql+asyncpg://user:password@db:5432/granite
    env_file: ./backend/src/.env
    volumes:
      - ./backend/static:/app/static
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: granite_frontend
    networks:
      - dev

  db:
    image: postgres
    container_name: granite_db
    environment:
      POSTGRES_DB: granite
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - dev

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT/1080
      - MAILDEV_SMTP_PORT/1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - dev

  telebot:
    build:
      context: ./telebot
      dockerfile: Dockerfile
    container_name: granite_telebot
    env_file:
      - ./telebot/.env
    environment:
      - DB__URL=postgresql://user:password@db:5432/granite
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev

volumes:
  pgdata:
