services:
  backend:
    build: .
    container_name: granite_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    env_file: ./src/.env
    depends_on:
      - db

  db:
    image: postgres
    container_name: granite_db
    environment:
      POSTGRES_DB: granite
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
